# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c72566a53c9c9a8a9d1dd7c25a8a5637e2dde2ff13853b95cdb635d307fa567a3b17750bbb688b85a9248b72f400188f9a5feb66bc05df04a8ba2926878bdd7b

test:
  secret_key_base: f693b8b40b809afd6b657aaa9cd8ad1b2bb1ca78ba1bf5aa3d8a376ae6ed0f6c4bcf3962540e525e5fd285126124ec98a8a198c7976dd619cedec1ae559e86d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
